# For Windows
# [shell]
# program = 'Ubuntu'

[font]
size = 17.0

[font.normal]
family = "Adwaita Mono"
style = "Regular"

[font.bold]
family = "Adwaita Mono"
style = "Bold"

[font.bold_italic]
family = "Adwaita Mono"
style = "Bold Italic"

[font.italic]
family = "Adwaita Mono"
style = "Italic"

[window]
opacity = 0.85
blur = true
padding = { x = 10, y = 10 }

[cursor]
style = { shape = "Block", blinking = "Off" }

[colors]
selection = { text = "#0f0f0f" , background = "#c4c4b5" }

[colors.primary]
foreground = "#c4c4b5"
background = "#0f0f0f" 

[colors.normal]
black = "#191919"
red = "#f3005f"
green = "#97e023"
yellow = "#f2f200"
blue = "#007acc"
magenta = "#9c64fe"
cyan = "#57d1ea"
white = "#c4c4b5"
